name = "fied-relay"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "fied.app", custom_domain = true }
]

[vars]
MAX_VIEWERS_PER_SESSION = "5"

[assets]
directory = "../web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [
  { name = "SESSION", class_name = "Session" },
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["Session"]

[[migrations]]
tag = "v2"
new_classes = ["RateLimiter"]
