name = "fied-relay"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "fied.app", custom_domain = true }
]

[assets]
directory = "../web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[durable_objects]
bindings = [
  { name = "SESSION", class_name = "Session" }
]

[[migrations]]
tag = "v1"
new_classes = ["Session"]
